title: Kunal Indore
logo: /assets/img/IMG_20190415_112047-01-EDIT.jpg
description: Analyzing the World, One Dataset at a Time
show_downloads: false
theme: jekyll-theme-minimal
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/kunal-indore/
  - title: GitHub
    url: https://github.com/Kunal18
